# Generated by Django 3.0.7 on 2020-06-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_book_copy_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id_hero', models.IntegerField(primary_key=True, serialize=False)),
                ('name_hero', models.CharField(blank=True, max_length=50, null=True)),
                ('level_hero', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('currentexp', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('hit_point', models.IntegerField(blank=True, null=True)),
                ('count_heal_day', models.IntegerField(blank=True, null=True)),
                ('heal_value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'heroes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeroesClassDic',
            fields=[
                ('id_class', models.IntegerField(primary_key=True, serialize=False)),
                ('name_class', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'heroes_class_dic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeroesParamDic',
            fields=[
                ('id_param', models.IntegerField(primary_key=True, serialize=False)),
                ('name_param', models.CharField(max_length=30)),
                ('short_name_field', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'heroes_param_dic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeroesRacesDic',
            fields=[
                ('id_race', models.IntegerField(primary_key=True, serialize=False)),
                ('name_race', models.CharField(max_length=30)),
                ('count_languages', models.IntegerField(blank=True, null=True)),
                ('language_default', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'heroes_races_dic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeroesTypeParamDic',
            fields=[
                ('id_type_param', models.IntegerField(primary_key=True, serialize=False)),
                ('name_type_param', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'heroes_type_param_dic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('guid_player', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('password_pl', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TraitsDic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_field', models.IntegerField()),
                ('name_field', models.CharField(blank=True, max_length=99, null=True)),
                ('requirements_field', models.CharField(blank=True, max_length=1999, null=True)),
                ('description_field', models.CharField(blank=True, max_length=1999, null=True)),
            ],
            options={
                'db_table': 'traits_dic',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.CreateModel(
            name='HeroesParamAddflArray',
            fields=[
                ('id_hero', models.OneToOneField(db_column='id_hero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='p_library.Heroes')),
                ('training', models.BooleanField()),
                ('field_int', models.IntegerField(blank=True, null=True)),
                ('field_string', models.CharField(blank=True, max_length=100, null=True)),
                ('field_money', models.TextField(blank=True, null=True)),
                ('modify_param', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'heroes_param_addfl_array',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RaceParamDefault',
            fields=[
                ('id_race', models.OneToOneField(db_column='id_race', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='p_library.HeroesRacesDic')),
                ('field_default', models.IntegerField(blank=True, null=True)),
                ('add_param_choice', models.BooleanField(blank=True, null=True)),
                ('add_param_default', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'race_param_default',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
