# Generated by Django 3.0.7 on 2020-06-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_auto_20200614_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('birth_year', models.SmallIntegerField()),
                ('country', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(db_column='ISBN', max_length=13)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('year_release', models.SmallIntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('copy_count', models.SmallIntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='p_library.Author')),
            ],
        ),
        migrations.DeleteModel(
            name='HeroesClassDic',
        ),
        migrations.RemoveField(
            model_name='heroesparamaddflarray',
            name='id_hero',
        ),
        migrations.DeleteModel(
            name='HeroesParamDic',
        ),
        migrations.DeleteModel(
            name='HeroesTypeParamDic',
        ),
        migrations.DeleteModel(
            name='Players',
        ),
        migrations.RemoveField(
            model_name='raceparamdefault',
            name='id_race',
        ),
        migrations.DeleteModel(
            name='TraitsDic',
        ),
        migrations.DeleteModel(
            name='Heroes',
        ),
        migrations.DeleteModel(
            name='HeroesParamAddflArray',
        ),
        migrations.DeleteModel(
            name='HeroesRacesDic',
        ),
        migrations.DeleteModel(
            name='RaceParamDefault',
        ),
    ]
