# Generated by Django 3.0.7 on 2020-06-24 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0009_auto_20200624_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='publish', to='p_library.Publishing'),
        ),
    ]
